/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_clinicas;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.beans.Statement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brhb2
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    DatabaseConnector dbConnector = new DatabaseConnector();

    public Main() throws SQLException {
        initComponents();
        
        try {
            coneccionOracle = dbConnector.getOracleConnection();
            coneccionMySQL = dbConnector.getMySQLConnection();

        } catch (SQLException ex) {
             traducirError(ex);
        }
     
   inicartbale2();
        iniciartable1();
    }

    void inicartbale2() {

        String sql = "SELECT * FROM " + jC_Tabla.getSelectedItem().toString() + " ORDER BY 1 DESC LIMIT 5";
        DefaultTableModel modelo = (DefaultTableModel) jTable_Base2.getModel();
        modelo.setRowCount(0);
        modelo.setColumnCount(0);
        try {
            pst = coneccionMySQL.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            meta = (ResultSetMetaData) rs.getMetaData();
            int columnas = meta.getColumnCount();
            for (int i = 1; i <= columnas; i++) {
                modelo.addColumn(meta.getColumnLabel(i));
            }
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            jTable_Base2.setModel(modelo);

        } catch (SQLException ex) {
           traducirError(ex);
        }
    }

    void iniciartable1() {

        String sql1 = "SELECT * FROM " + jC_Tabla.getSelectedItem() + " ORDER BY 1 DESC FETCH FIRST 5 ROWS ONLY";
        DefaultTableModel modelo1 = (DefaultTableModel) JTable_Base1.getModel();
        modelo1.setRowCount(0);
        modelo1.setColumnCount(0);
       try {
    PreparedStatement pstoc = coneccionOracle.prepareStatement(sql1);
    ResultSet rs = pstoc.executeQuery();
            java.sql.ResultSetMetaData metaoc = rs.getMetaData(); 

    int columnas = metaoc.getColumnCount();

    for (int i = 1; i <= columnas; i++) {
        modelo1.addColumn(metaoc.getColumnLabel(i));
    }

    while (rs.next()) {
        Object[] fila = new Object[columnas];
        for (int i = 0; i < columnas; i++) {
            fila[i] = rs.getObject(i + 1);
        }
        modelo1.addRow(fila);
    }

    JTable_Base1.setModel(modelo1);

} catch (SQLException ex) {
    traducirError(ex);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_Replicar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Base1 = new javax.swing.JTable();
        jC_Tabla = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Base2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Btn_Replicar.setText("REPLICAR");
        Btn_Replicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReplicarActionPerformed(evt);
            }
        });

        JTable_Base1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Atributo 1", "Atributo 2", "Atributo 3", "Atributo 4", "Atributo 5", "Atributo 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_Base1);
        if (JTable_Base1.getColumnModel().getColumnCount() > 0) {
            JTable_Base1.getColumnModel().getColumn(0).setResizable(false);
            JTable_Base1.getColumnModel().getColumn(1).setResizable(false);
            JTable_Base1.getColumnModel().getColumn(2).setResizable(false);
            JTable_Base1.getColumnModel().getColumn(3).setResizable(false);
            JTable_Base1.getColumnModel().getColumn(4).setResizable(false);
            JTable_Base1.getColumnModel().getColumn(5).setResizable(false);
        }

        jC_Tabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "paciente", "clinica", "doctor", "cita", "historial_medico", "receta ", "medicamento", "receta_medicamento " }));
        jC_Tabla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_TablaItemStateChanged(evt);
            }
        });

        jTable_Base2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Atributo 1", "Atributo 2", "Atributo 3", "Atributo 4", "Atributo 5", "Atributo 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Base2);
        if (jTable_Base2.getColumnModel().getColumnCount() > 0) {
            jTable_Base2.getColumnModel().getColumn(0).setResizable(false);
            jTable_Base2.getColumnModel().getColumn(1).setResizable(false);
            jTable_Base2.getColumnModel().getColumn(2).setResizable(false);
            jTable_Base2.getColumnModel().getColumn(3).setResizable(false);
            jTable_Base2.getColumnModel().getColumn(4).setResizable(false);
            jTable_Base2.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione Tabla");

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Replicador Bidireccional");

        jLabel2.setText("Oracle");

        jLabel5.setText("MySQL");

        jButton1.setText("Refresh table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(206, 206, 206))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jC_Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(jLabel5)
                .addGap(196, 196, 196))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Replicar)
                .addGap(544, 544, 544))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jC_Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(Btn_Replicar)
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ReplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReplicarActionPerformed

     try (CallableStatement stmt1 = coneccionOracle.prepareCall("{call replicar_mysql_a_oracle}")) {
            stmt1.execute();
            System.out.println("replicar_mysql_a_oracle ejecutado correctamente.");
        } catch (SQLException ex) {
             traducirError(ex);
        }
        try (var stmt2 = coneccionOracle.prepareCall("{call replicar_oracle_a_mysql}")) {
            stmt2.execute();
            System.out.println("replicar_oracle_a_mysql ejecutado correctamente.");
        } catch (SQLException ex) {
             traducirError(ex);

        }
        try {
            coneccionOracle.commit();
        } catch (SQLException ex) {
            traducirError(ex);
        }
       
        
    }//GEN-LAST:event_Btn_ReplicarActionPerformed

    private void jC_TablaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_TablaItemStateChanged

           inicartbale2();
         iniciartable1();

    }//GEN-LAST:event_jC_TablaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           inicartbale2();
        iniciartable1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private static void traducirError(SQLException e) {
        String mensaje = e.getMessage();
        String mensaje2;

        if (mensaje == null || mensaje.isEmpty()) {
            mensaje2 = "Ocurrió un error inesperado. Por favor, intente nuevamente.";
        } else if (mensaje.contains("Duplicate entry")) {
            mensaje2 = "Parece que ya existe un registro con este valor. Por favor, verifica e intente nuevamente.";
        } else if (mensaje.contains("Incorrect integer value")) {
            mensaje2 = "El valor ingresado no es válido. Asegúrate de ingresar un número entero correcto o de no dejar vacio los identificadores.";
        } else if (mensaje.contains("Access denied")) {
            mensaje2 = "No tienes permiso para realizar esta acción. Verifica tus credenciales e intente nuevamente.";
        } else if (mensaje.contains("SQL syntax")) {
            mensaje2 = "Hubo un problema con la consulta. Por favor, verifica la información e intente nuevamente.";
        } else if (mensaje.contains("foreign key constraint")) {
           
                mensaje2 = "No se puede dejar en blanco un identificador secundario o escoger uno que no existe, agrege uno existente e intente nuevamente.";
            

        } else if (mensaje.contains("Data too long")) {
            mensaje2 = "El dato ingresado es demasiado largo. Por favor, verifica la longitud del dato e intente nuevamente.";
        } else if (mensaje.contains("No database selected")) {
            mensaje2 = "No se ha seleccionado una base de datos. Por favor, selecciona una base de datos e intente nuevamente.";
        } else if (mensaje.contains("connection closed")) {
            mensaje2 = "No se ha seleccionado una base de datos. Por favor, Conectese a una Base de Datos e intente nuevamente.";
        } else if (mensaje.contains("Invalid date format")) {
            mensaje2 = "El formato de la fecha ingresada no es válido. Por favor, verifica el formato e intente nuevamente.";
        } else if (mensaje.contains("Cannot add or update a child row")) {
            mensaje2 = "No se puede agregar o actualizar un registro debido a una relación con otro registro. Verifica que los registros relacionados existan e intente nuevamente.";
        } else if (mensaje.contains("Data truncation")) {
            mensaje2 = "Parece que hay un problema con los datos ingresados. Por favor, revisa que estén correctos y en el formato adecuado.";
        } else if (mensaje.contains("Incorrect decimal value")) {
            mensaje2 = "El valor ingresado no es válido. Asegúrate de ingresar un número decimal correcto.";
        } else if (mensaje.contains("Check constraint")) {

            mensaje2 = "accion restringida esta tratando de ingresar un valor no permitido. Por favor, verifica los datos e intente nuevamente.";

        } else {
            mensaje2 = "Ocurrió un error inesperado: " + mensaje + ". Por favor, intente nuevamente.";
        }

     
        JOptionPane.showMessageDialog(null, mensaje2);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    traducirError(ex);
                }
            }
        });
    }
    
    
    PreparedStatement pst = null;
    Connection coneccionOracle = null;
    Connection coneccionMySQL = null;
    ResultSetMetaData meta = null;
    ResultSetMetaData metaoc = null;
    PreparedStatement pstoc = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Replicar;
    private javax.swing.JTable JTable_Base1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jC_Tabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_Base2;
    // End of variables declaration//GEN-END:variables
}
